# Generated by Django 4.0.4 on 2022-06-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='gallery')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
